# Site settings
title: Erick Dennis
# description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edennis.github.io"
twitter_username: _edennis
github_username:  edennis
disqus:
  shortname: edennis

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
